// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using _2TDSPJ.API.Persitence;

#nullable disable

namespace _2TDSPJ.API.Migrations
{
    [DbContext(typeof(OracleDBContext))]
    partial class OracleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuartoTipoQuarto", b =>
                {
                    b.Property<int>("QuartosQuartoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoQuartosTipoQuartoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("QuartosQuartoId", "TipoQuartosTipoQuartoId");

                    b.HasIndex("TipoQuartosTipoQuartoId");

                    b.ToTable("QuartoTipoQuarto");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Hospede", b =>
                {
                    b.Property<int>("HospedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospedeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("HospedeId");

                    b.ToTable("TB_HOSPEDE");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Pagamento", b =>
                {
                    b.Property<int>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagamentoId"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("PagamentoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("TB_PAGAMENTO");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Quarto", b =>
                {
                    b.Property<int>("QuartoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuartoId"));

                    b.Property<string>("NumeroQuarto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoPorNoite")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("QuartoId");

                    b.ToTable("TB_QUARTO");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("HospedeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuartoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("ReservaId");

                    b.HasIndex("HospedeId");

                    b.HasIndex("QuartoId");

                    b.ToTable("TB_RESERVA");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.TipoQuarto", b =>
                {
                    b.Property<int>("TipoQuartoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoQuartoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("TipoQuartoId");

                    b.ToTable("TB_TIPOQUARTO");
                });

            modelBuilder.Entity("QuartoTipoQuarto", b =>
                {
                    b.HasOne("_2TDSPJ.API.Persitence.Models.Quarto", null)
                        .WithMany()
                        .HasForeignKey("QuartosQuartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2TDSPJ.API.Persitence.Models.TipoQuarto", null)
                        .WithMany()
                        .HasForeignKey("TipoQuartosTipoQuartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Pagamento", b =>
                {
                    b.HasOne("_2TDSPJ.API.Persitence.Models.Reserva", "Reserva")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Reserva", b =>
                {
                    b.HasOne("_2TDSPJ.API.Persitence.Models.Hospede", "Hospede")
                        .WithMany("Reservas")
                        .HasForeignKey("HospedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2TDSPJ.API.Persitence.Models.Quarto", "Quarto")
                        .WithMany()
                        .HasForeignKey("QuartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospede");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Hospede", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("_2TDSPJ.API.Persitence.Models.Reserva", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
